# project_ef21_extension: Script generators 

In [2]:
%matplotlib inline
import numpy as np
from sklearn.model_selection import train_test_split
import time
import sys
import os
import argparse
from numpy.random import normal, uniform
from sklearn.datasets import make_spd_matrix, make_sparse_spd_matrix, load_svmlight_file, dump_svmlight_file
from numpy.linalg import norm
import itertools
from scipy.special import binom
from scipy.stats import ortho_group
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import f1_score, accuracy_score
import pandas as pd
from matplotlib import pyplot as plt
import math
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.datasets import load_svmlight_file
import datetime
from IPython import display
#from logreg_functions_fast import *

from contextlib import redirect_stdout
import shutil
import subprocess

## Bash script generator

# Full gradient case for generaly non-convex functions  with theoretical stepsize

In [9]:
np.linspace (max(int(0.01*100),1), 100, num_plot_points, endpoint=False, dtype=int)

array([ 1, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [70]:
myrepr = lambda x: repr(round(x, 4)).replace('.',',') if isinstance(x, float) else repr(x)

def read_file (shell_script_name, print_each_script):
    if print_each_script:
        f = open(shell_script_name, 'r')
        print(f.read())
        f.close()

project_path = os.getcwd() + "/"

methods_ar = ["tournament", "quick_random", "quick_det", "quick_med"]
distribution_family_ar = ["uniform", "normal"]
mean = 0
sigma_ar = [1,10,100]
left = -10
right = 10
n_samples = 10_000
d_ar = np.array([10**2, 10**3], dtype=int)
num_plot_points = 10

k_ar_100 = np.linspace (max(int(0.01*100),1), 100, num_plot_points, endpoint=False, dtype=int)

time = 12
cpus_per_task = 1
memmory = 8

print_each_script = 1
print_global_script = 1

shell_script_name = "slurm_ef21_hb_k1-16_f64"

single_experiment_name = "mwap"


print ("bash "+shell_script_name + ".sh\n")

#ef21-pp_nw-{0}_{1}x_{2}

with open(shell_script_name + ".sh", 'w') as f1:
    if "tournament" in exps:
        for distribution_family in distribution_family_ar:
            for i_d, d in enumerate (d_ar):
                k_ar = k_ar_100 * int(d/100)
                for i_k,k in enumerate(k_ar):
                    script_name = shell_script_name+"_"+"tournament_"+single_experiment_name +f"_{i}" + ".sh"
                    with open(script_name, 'w') as f:
                        with redirect_stdout(f):
                            print ("#!/bin/bash")
                            if distribution_family = "normal":
                                print (f"synthetic_tournament_normal.py  --d {d} --k {k}--n_samples {n_samples} --mean {mean} --sigma")
                            if distribution_family = "uniform":
                                print (f"synthetic_tournament_normal.py  --d {d} --k {k}--n_samples {n_samples}")
                    f1.write ("sbatch --cpus-per-task={3} --mem={4}GB --time={2}:00:00 {0}{1}\n".format(project_path, script_name, time, cpus_per_task, memmory))
                    read_file (script_name, print_each_script)

if print_global_script:    
    f = open(shell_script_name + ".sh", 'r')
    print(f.read())
    f.close()


bash slurm_ef21_pp_k1-64_f025-256_prw_4_mwap.sh

Number of experiments:  1540
#!/bin/bash
python3 ef21_pp.py --k 1 --dataset mushrooms --max_it 100000 --tol 1e-07 --factor 0.25 --num_workers 100 --prw 0.125

#!/bin/bash
python3 ef21_pp.py --k 1 --dataset mushrooms --max_it 100000 --tol 1e-07 --factor 0.25 --num_workers 100 --prw 0.065

#!/bin/bash
python3 ef21_pp.py --k 1 --dataset mushrooms --max_it 100000 --tol 1e-07 --factor 0.25 --num_workers 100 --prw 0.03

#!/bin/bash
python3 ef21_pp.py --k 1 --dataset mushrooms --max_it 100000 --tol 1e-07 --factor 0.25 --num_workers 100 --prw 0.015

#!/bin/bash
python3 ef21_pp.py --k 1 --dataset mushrooms --max_it 100000 --tol 1e-07 --factor 0.25 --num_workers 100 --prw 0.007

#!/bin/bash
python3 ef21_pp.py --k 1 --dataset mushrooms --max_it 100000 --tol 1e-07 --factor 0.5 --num_workers 100 --prw 0.125

#!/bin/bash
python3 ef21_pp.py --k 1 --dataset mushrooms --max_it 100000 --tol 1e-07 --factor 0.5 --num_workers 100 --prw 0.065

#!/bin/bash
pyt

In [3]:
num_plot_points = 10
d = 10_000
k_ar = np.linspace (max(int(0.01*d),1), d, num_plot_points, dtype=int)
k_ar[6]

6700

In [6]:
num_plot_points = 10
d_ar = np.array([10**2, 10**3], dtype=int)
for d in d_ar:
    print( np.linspace (max(int(0.01*d),1), d, num_plot_points, endpoint=False, dtype=int))

[ 1 10 20 30 40 50 60 70 80 90]
[ 10 109 208 307 406 505 604 703 802 901]


In [65]:
%%bash
bash slurm_ef21_pp_k32-64_f025-2048_mwap.sh

Submitted batch job 17187558
Submitted batch job 17187559
Submitted batch job 17187560
Submitted batch job 17187561
Submitted batch job 17187562
Submitted batch job 17187563
Submitted batch job 17187564
Submitted batch job 17187565
Submitted batch job 17187566
Submitted batch job 17187567
Submitted batch job 17187568
Submitted batch job 17187569
Submitted batch job 17187570
Submitted batch job 17187571
Submitted batch job 17187572
Submitted batch job 17187573
Submitted batch job 17187574
Submitted batch job 17187575
Submitted batch job 17187576
Submitted batch job 17187577
Submitted batch job 17187578
Submitted batch job 17187579
Submitted batch job 17187580
Submitted batch job 17187581
Submitted batch job 17187582
Submitted batch job 17187583
Submitted batch job 17187584
Submitted batch job 17187585
Submitted batch job 17187586
Submitted batch job 17187587
Submitted batch job 17187588
Submitted batch job 17187589
Submitted batch job 17187590
Submitted batch job 17187591
Submitted batc

In [30]:
%%bash
bash slurm_gd_f025-2048_mwap.sh

Submitted batch job 17123877
Submitted batch job 17123878
Submitted batch job 17123879
Submitted batch job 17123880
Submitted batch job 17123881
Submitted batch job 17123882
Submitted batch job 17123883
Submitted batch job 17123884
Submitted batch job 17123885
Submitted batch job 17123886
Submitted batch job 17123887
Submitted batch job 17123888
Submitted batch job 17123889
Submitted batch job 17123890
Submitted batch job 17123891
Submitted batch job 17123892
Submitted batch job 17123893
Submitted batch job 17123894
Submitted batch job 17123895
Submitted batch job 17123896
Submitted batch job 17123897
Submitted batch job 17123898
Submitted batch job 17123899
Submitted batch job 17123900
Submitted batch job 17123901
Submitted batch job 17123902
Submitted batch job 17123903
Submitted batch job 17123904
Submitted batch job 17123905
Submitted batch job 17123906
Submitted batch job 17123907
Submitted batch job 17123908
Submitted batch job 17123909
Submitted batch job 17123910
Submitted batc